### ISSUE TITLE
Read.md

### ISSUE THREAD

**Issue by alexbgameson** [thebigsmileXD/TileFixer#1]
Yes, you can! Contributions are welcomed provided that they comply with our [Contributing Guidelines](CONTRIBUTING.md). Please ensure you read the relevant sections of the guidelines carefully before making a Pull Request or opening an Issue.
  
  ### Where can I get the latest .phar?
 -<<<<<<< HEAD
 - - You can get the latest auto build phar for cs-1.0 here: https://phar.wolvesfortress.de/circleci.php?branch=cs-1.0
 - - [CSPhar](http://robskebueba.no-ip.biz/CSPhar.php) or [CSPhar by Dan](https://phar.wolvesfortress.de) are beta websites to easily show all builds
 -=======
 - - Currently, you can't. We are working on adding it back though.
 - - You can get the latest auto build phar here: [CSPhar](http://robskebueba.no-ip.biz/CSPhar.php) or [CSPhar by Dan](http://wolvesfortress.de/phar/CSPhar/CSPhar.php) (beta)
 ->>>>>>> master
 + - You can get the latest auto build phar here: [CSPhar-Direct](https://phar.wolvesfortress.de/circleci.php?branch=cs-1.0) (beta)
 + - You can get an overview of phar builds here: [CSPhar](https://phar.wolvesfortress.de) (beta)
   - You can get an optimized PHP environment here: [SalmonGER/PHPbinary](https://github.com/SalmonGER/PocketMine-MP-Binarys).
   - You can get a Multicraft config demo here: [ClearSkyTeam/MulticraftConfig](https://github.com/ClearSkyTeam/MulticraftConfig).

Where does it say that branch v11 doesnt work?

**Comment by thebigsmileXD** [comment]
this is tilefixer.
